Feature/login view
APP-iOS5th/FinalProject-Kabinett pull request #60
Opened 2024-08-23 06:51 UTC by YuleGlycerine

### 📕 Issue Number

Close #12 

### 📙 작업 내역

> 익명로그인 화면과 애플로그인을 통한 회원가입 기능 구현

- [x] 익명 유저 화면 UI
- [x] 프로토콜 채택한 가짜객체 작성
- [x] SignUpUseCaseStub과 SignUpViewModel 연동
- [x] 회원가입 화면(이름, 고유번호) UI
- [x] 카비넷 넘버 생성 로직
- [x] 애플로그인 구현

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
- [x] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 넘 과정이 길어지는 것 같아서 요 정도로 끊어서 PR을 올립니당~ 아래는 이어서 추가할 기능들이에요 ~🍅
-- 회원가입 과정 도중 종료하거나 Back 버튼을 누르는 경우는 아직 대응하지 못했어요.
-- 회원가입에 실패하는 경우 알럿창을 띄우는 코드를 추가해야해요.
-- 지금은 애플 로그인 버튼이 영어로 보이고 있는데 ko를 추가해야해요.

![LoginViewPR](https://github.com/user-attachments/assets/21a9223b-a17c-44d0-9c0f-71d2b2dbc7b1)
<br/><br/>

2024-08-23 07:28 UTC, jinwoong16 requested changes
고생하셨어요~
변경해볼만한 부분은 같이 이야기해볼 수 있을 것 같네요!
디자인도 하고 개발도 잘해주셔서 감사해요 :) 너무 고생 많으셨어요 !

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Presentation/View/Profile/SignUpKabinettNumberSelectView.swift
> +        NavigationView{
NavigationView는 deprecated되었다고 나올거에요!
`NavigationStack`을 사용해주시면 될 것 같아요

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Application/KabinettApp.swift
> +            SignUpNameInputView(viewModel: SignUpViewModel(useCase: SignUpUseCaseStub()))
가짜객체를 생성자로 주입해주는 거 좋아요~

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Presentation/View/Profile/SignUpKabinettNumberSelectView.swift
> +    @Environment(\.presentationMode) var presentationMode
`PresentationMode`는 deprecated에요.
화면을 종료하는 `dismiss`를 사용하는 것이 목적이면 
```swift
@Environment(\.dismiss) var dismiss
```
를 사용해주세요 :)

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Presentation/View/Profile/SignUpNameInputView.swift
> +    @StateObject var viewModel: SignUpViewModel
상위뷰에서 이곳으로 view model을 넘겨주는거라면 `ObservedObject`를 사용해주세요!
단, 상위 뷰에서는 `StateObject`를 사용해서 view model을 가지고 있어야 해요.

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Presentation/ViewModel/Profile/SignUpViewModel.swift
> +
요 부분은 추가적인 로직 없이, `ASAuthorization`만 뽑아서 유즈케이스로 보내주면 될 것 같아요!

2024-08-23 07:28 UTC, jinwoong16 commented on Kabinett/Presentation/ViewModel/Profile/SignUpViewModel.swift
> +                }
이 부분은 메인 스레드에서 동작시키려는 것 같아요
가장 상단의 `MainActor`를 안쓰고 
```swift
Task { @MainAction in 
...
}
```
위처럼 메인액터에서 동작하는 `Task`를 사용해주면 될 것 같아요.

추가적으로 유즈케이스를 실행하는 부분만 있으면 될 것 같구,.. 아래 부분은 없어도 될 것 같아요. 해당 부분은 데이터쪽 개발에서 사용할 것 같아요~~

2024-08-26 03:58 UTC, jinwoong16 approved these changes

2024-08-26 04:05 UTC, the-hye approved these changes

2024-08-26 04:06 UTC, merged